// Weather phrase categories based on weather code and temperature
export type WeatherCategory = 
  | 'sunny_hot' 
  | 'sunny_mild' 
  | 'cloudy' 
  | 'rain' 
  | 'storm' 
  | 'snow' 
  | 'fog' 
  | 'cold' 
  | 'windy';

export type SupportedLanguage = 'pt-BR' | 'en-US' | 'es-ES' | 'fr-FR' | 'de-DE' | 'it-IT' | 'ja-JP' | 'ko-KR' | 'zh-CN';

export interface WeatherPhrase {
  text: string;
  emoji: string;
}

// Map weather code to category
export function getWeatherCategory(weatherCode: number, temperature: number): WeatherCategory {
  // Thunderstorm
  if (weatherCode >= 95) return 'storm';
  
  // Snow
  if (weatherCode >= 71 && weatherCode <= 77) return 'snow';
  
  // Rain/Drizzle
  if ((weatherCode >= 51 && weatherCode <= 67) || (weatherCode >= 80 && weatherCode <= 82)) return 'rain';
  
  // Fog
  if (weatherCode >= 45 && weatherCode <= 48) return 'fog';
  
  // Cloudy
  if (weatherCode >= 1 && weatherCode <= 3) return 'cloudy';
  
  // Clear sky - check temperature
  if (weatherCode === 0) {
    if (temperature >= 30) return 'sunny_hot';
    if (temperature <= 10) return 'cold';
    return 'sunny_mild';
  }
  
  // Default based on temperature
  if (temperature >= 30) return 'sunny_hot';
  if (temperature <= 10) return 'cold';
  
  return 'cloudy';
}

// Phrases organized by category and language
const phrases: Record<WeatherCategory, Record<SupportedLanguage, WeatherPhrase[]>> = {
  sunny_hot: {
    'pt-BR': [
      { text: "Tá tão quente que até o diabo tá reclamando", emoji: "😈" },
      { text: "Clima perfeito pra piscina e churras!", emoji: "🏊‍♂️" },
      { text: "Esse calor tá igual senha de WiFi: impossível", emoji: "🥵" },
      { text: "Hoje o sol acordou violento", emoji: "☀️" },
      { text: "Perfeito pra um açaí bem gelado", emoji: "🍇" },
      { text: "Tá um calor de derreter até pensamento", emoji: "🫠" },
      { text: "Dia de praia, sem discussão", emoji: "🏖️" },
      { text: "O ar condicionado é meu melhor amigo hoje", emoji: "❄️" },
    ],
    'en-US': [
      { text: "It's giving Sahara Desert vibes", emoji: "🏜️" },
      { text: "Perfect pool day, no excuses", emoji: "🏊" },
      { text: "The sun chose violence today", emoji: "☀️" },
      { text: "Ice cream emergency activated", emoji: "🍦" },
      { text: "SPF 100 kinda day", emoji: "🧴" },
      { text: "Hot girl summer is REAL", emoji: "💅" },
      { text: "AC on full blast mode", emoji: "❄️" },
      { text: "Time to become one with the pool", emoji: "🌊" },
    ],
    'es-ES': [
      { text: "Hoy me derrito como helado", emoji: "🍦" },
      { text: "Perfecto para una cerveza bien fría", emoji: "🍺" },
      { text: "El sol está en modo venganza", emoji: "☀️" },
      { text: "Día de playa obligatorio", emoji: "🏖️" },
      { text: "Calor infernal, literalmente", emoji: "🔥" },
      { text: "El aire acondicionado es vida", emoji: "❄️" },
      { text: "Ni los helados sobreviven hoy", emoji: "🫠" },
      { text: "Perfecto para una siesta", emoji: "😴" },
    ],
    'fr-FR': [
      { text: "On fond comme du beurre au soleil", emoji: "🧈" },
      { text: "Parfait pour une glace", emoji: "🍨" },
      { text: "Le soleil est en mode warrior", emoji: "☀️" },
      { text: "Direction la plage!", emoji: "🏖️" },
      { text: "Canicule activée", emoji: "🥵" },
      { text: "Vive la clim!", emoji: "❄️" },
      { text: "Journée piscine obligatoire", emoji: "🏊" },
      { text: "Même les glaçons fondent", emoji: "🧊" },
    ],
    'de-DE': [
      { text: "Perfektes Freibad-Wetter!", emoji: "🏊" },
      { text: "Zeit für ein kühles Bier", emoji: "🍺" },
      { text: "Die Sonne meint es ernst", emoji: "☀️" },
      { text: "Eis-Notfall aktiviert", emoji: "🍦" },
      { text: "Ab an den See!", emoji: "🏖️" },
      { text: "Klimaanlage auf Maximum", emoji: "❄️" },
      { text: "Heute schmelzen wir alle", emoji: "🫠" },
      { text: "Sonnenbrand-Gefahr!", emoji: "🧴" },
    ],
    'it-IT': [
      { text: "Perfetto per un gelato!", emoji: "🍨" },
      { text: "Il sole oggi è cattivo", emoji: "☀️" },
      { text: "Giornata da spiaggia", emoji: "🏖️" },
      { text: "Caldo da sciogliersi", emoji: "🫠" },
      { text: "Evviva l'aria condizionata!", emoji: "❄️" },
      { text: "Spritz time!", emoji: "🍹" },
      { text: "Oggi sudo anche a pensare", emoji: "🥵" },
      { text: "Perfetto per la piscina", emoji: "🏊" },
    ],
    'ja-JP': [
      { text: "今日は溶ける暑さだね〜", emoji: "🫠" },
      { text: "かき氷が必要！", emoji: "🍧" },
      { text: "エアコンなしでは無理", emoji: "❄️" },
      { text: "プール日和！", emoji: "🏊" },
      { text: "日焼け止め必須だよ", emoji: "🧴" },
      { text: "アイス食べたい気分", emoji: "🍦" },
      { text: "熱中症に気をつけて", emoji: "💦" },
      { text: "今日は暑すぎる〜", emoji: "🥵" },
    ],
    'ko-KR': [
      { text: "빙수 먹으러 가자!", emoji: "🍧" },
      { text: "에어컨 없으면 죽음", emoji: "☠️" },
      { text: "이 더위는 레전드야", emoji: "🔥" },
      { text: "수영장 가고 싶다", emoji: "🏊" },
      { text: "아이스 아메리카노 필수", emoji: "☕" },
      { text: "오늘 진짜 덥다", emoji: "🥵" },
      { text: "선크림 꼭 바르세요", emoji: "🧴" },
      { text: "녹아내리는 중...", emoji: "🫠" },
    ],
    'zh-CN': [
      { text: "热到怀疑人生", emoji: "🥵" },
      { text: "完美的游泳天气", emoji: "🏊" },
      { text: "空调救我狗命", emoji: "❄️" },
      { text: "西瓜冰棍安排上", emoji: "🍉" },
      { text: "出门就是烤肉", emoji: "🔥" },
      { text: "今天适合宅家吹空调", emoji: "🏠" },
      { text: "太阳今天火力全开", emoji: "☀️" },
      { text: "防晒霜涂起来", emoji: "🧴" },
    ],
  },
  sunny_mild: {
    'pt-BR': [
      { text: "Dia perfeito pra um passeio", emoji: "🚶" },
      { text: "Clima de novela das 6", emoji: "📺" },
      { text: "Bom demais pra ficar em casa", emoji: "🌤️" },
      { text: "Hoje tá uma beleza!", emoji: "✨" },
      { text: "Perfeito pra um café ao ar livre", emoji: "☕" },
      { text: "Dia de agradecer ao universo", emoji: "🙏" },
      { text: "Climinha bom pra tudo", emoji: "😎" },
      { text: "Aproveita que tá uma maravilha", emoji: "🌈" },
    ],
    'en-US': [
      { text: "Perfect vibes only today", emoji: "✨" },
      { text: "Main character weather", emoji: "🎬" },
      { text: "Too nice to stay inside", emoji: "🌤️" },
      { text: "Golden hour all day", emoji: "🌅" },
      { text: "Touch grass kinda day", emoji: "🌱" },
      { text: "Chef's kiss weather", emoji: "👨‍🍳" },
      { text: "No complaints allowed", emoji: "😎" },
      { text: "Nature is healing", emoji: "🌳" },
    ],
    'es-ES': [
      { text: "Día perfecto para pasear", emoji: "🚶" },
      { text: "Clima de postal", emoji: "📸" },
      { text: "Imposible quedarse en casa", emoji: "🌤️" },
      { text: "Qué día tan bonito", emoji: "✨" },
      { text: "Perfecto para una terracita", emoji: "☕" },
      { text: "El tiempo está de lujo", emoji: "😎" },
      { text: "Día para disfrutar", emoji: "🌈" },
      { text: "Gracias universo", emoji: "🙏" },
    ],
    'fr-FR': [
      { text: "Journée parfaite pour flâner", emoji: "🚶" },
      { text: "Temps de carte postale", emoji: "📸" },
      { text: "Trop beau pour rester dedans", emoji: "🌤️" },
      { text: "C'est magnifique!", emoji: "✨" },
      { text: "Parfait pour un café en terrasse", emoji: "☕" },
      { text: "Merci la vie", emoji: "🙏" },
      { text: "On profite!", emoji: "😎" },
      { text: "Le temps est au top", emoji: "🌈" },
    ],
    'de-DE': [
      { text: "Perfekter Tag für einen Spaziergang", emoji: "🚶" },
      { text: "Postkarten-Wetter", emoji: "📸" },
      { text: "Zu schön für drinnen", emoji: "🌤️" },
      { text: "Einfach wunderschön!", emoji: "✨" },
      { text: "Zeit für Kaffee im Freien", emoji: "☕" },
      { text: "Danke Universum", emoji: "🙏" },
      { text: "Traumwetter!", emoji: "😎" },
      { text: "Genießen wir es!", emoji: "🌈" },
    ],
    'it-IT': [
      { text: "Giornata perfetta per passeggiare", emoji: "🚶" },
      { text: "Tempo da cartolina", emoji: "📸" },
      { text: "Troppo bello per stare dentro", emoji: "🌤️" },
      { text: "Che bella giornata!", emoji: "✨" },
      { text: "Perfetto per un caffè all'aperto", emoji: "☕" },
      { text: "Grazie universo", emoji: "🙏" },
      { text: "Tempo fantastico!", emoji: "😎" },
      { text: "Da godere!", emoji: "🌈" },
    ],
    'ja-JP': [
      { text: "散歩日和だね〜", emoji: "🚶" },
      { text: "絵葉書みたいな天気", emoji: "📸" },
      { text: "家にいるのがもったいない", emoji: "🌤️" },
      { text: "最高の一日！", emoji: "✨" },
      { text: "オープンカフェでまったり", emoji: "☕" },
      { text: "感謝の一日", emoji: "🙏" },
      { text: "いい天気〜", emoji: "😎" },
      { text: "お出かけ日和！", emoji: "🌈" },
    ],
    'ko-KR': [
      { text: "산책하기 딱 좋은 날씨", emoji: "🚶" },
      { text: "엽서 같은 날씨", emoji: "📸" },
      { text: "집에 있기 아까워", emoji: "🌤️" },
      { text: "완벽한 하루!", emoji: "✨" },
      { text: "카페 테라스 가자", emoji: "☕" },
      { text: "감사한 날씨", emoji: "🙏" },
      { text: "날씨 진짜 좋다", emoji: "😎" },
      { text: "나들이 가자!", emoji: "🌈" },
    ],
    'zh-CN': [
      { text: "完美的散步天气", emoji: "🚶" },
      { text: "明信片般的好天气", emoji: "📸" },
      { text: "宅家太可惜了", emoji: "🌤️" },
      { text: "今天真美好！", emoji: "✨" },
      { text: "适合户外喝咖啡", emoji: "☕" },
      { text: "感恩这样的天气", emoji: "🙏" },
      { text: "天气绝了", emoji: "😎" },
      { text: "出去浪吧！", emoji: "🌈" },
    ],
  },
  cloudy: {
    'pt-BR': [
      { text: "Clima perfeito pra Netflix", emoji: "📺" },
      { text: "Céu tá pensativo hoje", emoji: "🤔" },
      { text: "Dia de preguiça assumida", emoji: "😴" },
      { text: "Parece que vai, mas não vai", emoji: "☁️" },
      { text: "Clima de domingo à tarde", emoji: "🛋️" },
      { text: "Perfeito pra maratonar séries", emoji: "🎬" },
      { text: "O sol tá de folga hoje", emoji: "😎" },
      { text: "Nublado master race", emoji: "☁️" },
    ],
    'en-US': [
      { text: "Perfect Netflix weather", emoji: "📺" },
      { text: "The sky is having an identity crisis", emoji: "🤔" },
      { text: "Cozy indoor vibes", emoji: "🛋️" },
      { text: "Looks like rain... or not?", emoji: "☁️" },
      { text: "Lazy day unlocked", emoji: "😴" },
      { text: "Binge-watching weather", emoji: "🎬" },
      { text: "Sun is on vacation", emoji: "✈️" },
      { text: "Clouds are doing their thing", emoji: "☁️" },
    ],
    'es-ES': [
      { text: "Perfecto para Netflix", emoji: "📺" },
      { text: "El cielo está indeciso", emoji: "🤔" },
      { text: "Día de sofá y manta", emoji: "🛋️" },
      { text: "¿Llueve o no llueve?", emoji: "☁️" },
      { text: "Modo perezoso activado", emoji: "😴" },
      { text: "Maratón de series", emoji: "🎬" },
      { text: "El sol se tomó el día libre", emoji: "✈️" },
      { text: "Nublado pero bonito", emoji: "☁️" },
    ],
    'fr-FR': [
      { text: "Parfait pour Netflix", emoji: "📺" },
      { text: "Le ciel hésite", emoji: "🤔" },
      { text: "Journée cocooning", emoji: "🛋️" },
      { text: "Il pleut ou pas?", emoji: "☁️" },
      { text: "Mode paresseux activé", emoji: "😴" },
      { text: "Marathon de séries", emoji: "🎬" },
      { text: "Le soleil est en RTT", emoji: "✈️" },
      { text: "Nuageux mais sympa", emoji: "☁️" },
    ],
    'de-DE': [
      { text: "Perfekt für Netflix", emoji: "📺" },
      { text: "Der Himmel kann sich nicht entscheiden", emoji: "🤔" },
      { text: "Gemütlicher Tag drinnen", emoji: "🛋️" },
      { text: "Regnet es oder nicht?", emoji: "☁️" },
      { text: "Faulenzer-Modus an", emoji: "😴" },
      { text: "Serien-Marathon!", emoji: "🎬" },
      { text: "Die Sonne hat frei", emoji: "✈️" },
      { text: "Bewölkt aber okay", emoji: "☁️" },
    ],
    'it-IT': [
      { text: "Perfetto per Netflix", emoji: "📺" },
      { text: "Il cielo è indeciso", emoji: "🤔" },
      { text: "Giornata da divano", emoji: "🛋️" },
      { text: "Piove o non piove?", emoji: "☁️" },
      { text: "Modalità pigra attivata", emoji: "😴" },
      { text: "Maratona di serie!", emoji: "🎬" },
      { text: "Il sole è in ferie", emoji: "✈️" },
      { text: "Nuvoloso ma carino", emoji: "☁️" },
    ],
    'ja-JP': [
      { text: "Netflix日和だね", emoji: "📺" },
      { text: "空も迷ってる", emoji: "🤔" },
      { text: "おうちでまったり", emoji: "🛋️" },
      { text: "降るのかな？", emoji: "☁️" },
      { text: "だらだらする日", emoji: "😴" },
      { text: "ドラマ一気見！", emoji: "🎬" },
      { text: "太陽はお休み中", emoji: "✈️" },
      { text: "曇りも悪くない", emoji: "☁️" },
    ],
    'ko-KR': [
      { text: "넷플릭스 날씨", emoji: "📺" },
      { text: "하늘도 고민 중", emoji: "🤔" },
      { text: "집순이/집돌이 모드", emoji: "🛋️" },
      { text: "비 오려나?", emoji: "☁️" },
      { text: "나른한 하루", emoji: "😴" },
      { text: "드라마 정주행!", emoji: "🎬" },
      { text: "태양 휴가 중", emoji: "✈️" },
      { text: "흐리지만 괜찮아", emoji: "☁️" },
    ],
    'zh-CN': [
      { text: "适合宅家看剧", emoji: "📺" },
      { text: "天空也在纠结", emoji: "🤔" },
      { text: "沙发躺平日", emoji: "🛋️" },
      { text: "下不下雨呢？", emoji: "☁️" },
      { text: "懒散模式开启", emoji: "😴" },
      { text: "追剧时间到！", emoji: "🎬" },
      { text: "太阳今天请假", emoji: "✈️" },
      { text: "阴天也挺好", emoji: "☁️" },
    ],
  },
  rain: {
    'pt-BR': [
      { text: "Alguém esqueceu de fechar a torneira lá em cima", emoji: "☔" },
      { text: "Dia de pegar o guarda-chuva e reclamar", emoji: "🌧️" },
      { text: "Netflix e coberta, sem discussão", emoji: "📺" },
      { text: "Perfeito pra um chocolate quente", emoji: "☕" },
      { text: "O céu tá chorando igual segunda-feira", emoji: "😢" },
      { text: "Chuva pra refrescar a alma", emoji: "💧" },
      { text: "Tá chovendo mais que opinião na internet", emoji: "🌧️" },
      { text: "Dia de playlist triste e café", emoji: "🎧" },
    ],
    'en-US': [
      { text: "Time to channel your inner British person", emoji: "🇬🇧" },
      { text: "Perfect Netflix and chill weather", emoji: "📺" },
      { text: "Even the clouds are crying today", emoji: "😢" },
      { text: "Hot chocolate emergency", emoji: "☕" },
      { text: "Umbrella check activated", emoji: "☔" },
      { text: "Cozy rain sounds loading", emoji: "🎧" },
      { text: "Perfect excuse to stay home", emoji: "🏠" },
      { text: "Nature's shower time", emoji: "🚿" },
    ],
    'es-ES': [
      { text: "Perfecto para quedarse en casa", emoji: "🏠" },
      { text: "Día de manta y peli", emoji: "📺" },
      { text: "El cielo está llorando", emoji: "😢" },
      { text: "Hora de un chocolate caliente", emoji: "☕" },
      { text: "No olvides el paraguas", emoji: "☔" },
      { text: "Lluvia relajante", emoji: "🎧" },
      { text: "Excusa perfecta para no salir", emoji: "🛋️" },
      { text: "Día de charcos", emoji: "💧" },
    ],
    'fr-FR': [
      { text: "Parfait pour rester au chaud", emoji: "🏠" },
      { text: "Journée plaid et film", emoji: "📺" },
      { text: "Le ciel pleure", emoji: "😢" },
      { text: "C'est l'heure du chocolat chaud", emoji: "☕" },
      { text: "N'oublie pas ton parapluie", emoji: "☔" },
      { text: "Pluie relaxante", emoji: "🎧" },
      { text: "Excuse parfaite pour ne pas sortir", emoji: "🛋️" },
      { text: "Jour de flaques", emoji: "💧" },
    ],
    'de-DE': [
      { text: "Perfekt zum Drinnenbleiben", emoji: "🏠" },
      { text: "Decke und Film-Tag", emoji: "📺" },
      { text: "Der Himmel weint", emoji: "😢" },
      { text: "Zeit für heiße Schokolade", emoji: "☕" },
      { text: "Regenschirm nicht vergessen!", emoji: "☔" },
      { text: "Entspannender Regen", emoji: "🎧" },
      { text: "Perfekte Ausrede zu Hause zu bleiben", emoji: "🛋️" },
      { text: "Pfützen-Tag", emoji: "💧" },
    ],
    'it-IT': [
      { text: "Perfetto per stare al calduccio", emoji: "🏠" },
      { text: "Giornata coperta e film", emoji: "📺" },
      { text: "Il cielo piange", emoji: "😢" },
      { text: "Ora della cioccolata calda", emoji: "☕" },
      { text: "Non dimenticare l'ombrello!", emoji: "☔" },
      { text: "Pioggia rilassante", emoji: "🎧" },
      { text: "Scusa perfetta per non uscire", emoji: "🛋️" },
      { text: "Giorno di pozzanghere", emoji: "💧" },
    ],
    'ja-JP': [
      { text: "おうちでぬくぬく日和", emoji: "🏠" },
      { text: "映画とブランケットの日", emoji: "📺" },
      { text: "空も泣いてるね", emoji: "😢" },
      { text: "ホットココアの時間", emoji: "☕" },
      { text: "傘忘れないでね！", emoji: "☔" },
      { text: "雨音が癒し", emoji: "🎧" },
      { text: "出かけなくていい理由", emoji: "🛋️" },
      { text: "水たまり注意！", emoji: "💧" },
    ],
    'ko-KR': [
      { text: "집에서 뒹굴뒹굴하기 좋은 날", emoji: "🏠" },
      { text: "이불 속 영화 감상", emoji: "📺" },
      { text: "하늘도 우는 날", emoji: "😢" },
      { text: "핫초코 타임", emoji: "☕" },
      { text: "우산 챙기세요!", emoji: "☔" },
      { text: "빗소리 힐링", emoji: "🎧" },
      { text: "안 나가도 되는 핑계", emoji: "🛋️" },
      { text: "물웅덩이 조심", emoji: "💧" },
    ],
    'zh-CN': [
      { text: "今天适合躺平看剧", emoji: "📺" },
      { text: "完美的宅家理由", emoji: "🏠" },
      { text: "天空也在哭泣", emoji: "😢" },
      { text: "热巧克力时间到", emoji: "☕" },
      { text: "别忘了带伞哦", emoji: "☔" },
      { text: "听雨声好治愈", emoji: "🎧" },
      { text: "不出门的好借口", emoji: "🛋️" },
      { text: "小心水坑", emoji: "💧" },
    ],
  },
  storm: {
    'pt-BR': [
      { text: "Zeus tá bravo hoje", emoji: "⚡" },
      { text: "Thor fazendo a festa lá em cima", emoji: "🔨" },
      { text: "Dia de ficar quietinho em casa", emoji: "🏠" },
      { text: "Tempestade de verdade, não é drill", emoji: "🌩️" },
      { text: "O céu tá fazendo show de rock", emoji: "🎸" },
      { text: "Melhor não arriscar sair", emoji: "😰" },
      { text: "Raios e trovões, modo dramático ON", emoji: "⛈️" },
      { text: "Natureza mostrando quem manda", emoji: "💪" },
    ],
    'en-US': [
      { text: "Zeus is throwing a tantrum", emoji: "⚡" },
      { text: "Thor is having a party up there", emoji: "🔨" },
      { text: "Stay home, it's chaos outside", emoji: "🏠" },
      { text: "Real storm, not a drill", emoji: "🌩️" },
      { text: "The sky is throwing a rave", emoji: "🎸" },
      { text: "Maybe don't risk going out", emoji: "😰" },
      { text: "Drama queen weather", emoji: "⛈️" },
      { text: "Nature flexing hard", emoji: "💪" },
    ],
    'es-ES': [
      { text: "Zeus está enfadado hoy", emoji: "⚡" },
      { text: "Thor de fiesta allá arriba", emoji: "🔨" },
      { text: "Mejor quedarse en casa", emoji: "🏠" },
      { text: "Tormenta real, esto no es simulacro", emoji: "🌩️" },
      { text: "El cielo está de concierto", emoji: "🎸" },
      { text: "Mejor no arriesgarse", emoji: "😰" },
      { text: "Modo dramático activado", emoji: "⛈️" },
      { text: "La naturaleza manda", emoji: "💪" },
    ],
    'fr-FR': [
      { text: "Zeus est en colère aujourd'hui", emoji: "⚡" },
      { text: "Thor fait la fête là-haut", emoji: "🔨" },
      { text: "Mieux vaut rester à la maison", emoji: "🏠" },
      { text: "Vraie tempête, pas un exercice", emoji: "🌩️" },
      { text: "Le ciel fait un concert", emoji: "🎸" },
      { text: "Mieux vaut ne pas sortir", emoji: "😰" },
      { text: "Mode dramatique activé", emoji: "⛈️" },
      { text: "La nature montre qui commande", emoji: "💪" },
    ],
    'de-DE': [
      { text: "Zeus ist heute wütend", emoji: "⚡" },
      { text: "Thor feiert da oben", emoji: "🔨" },
      { text: "Besser zu Hause bleiben", emoji: "🏠" },
      { text: "Echter Sturm, kein Scherz", emoji: "🌩️" },
      { text: "Der Himmel gibt ein Konzert", emoji: "🎸" },
      { text: "Besser nicht rausgehen", emoji: "😰" },
      { text: "Drama-Modus aktiviert", emoji: "⛈️" },
      { text: "Die Natur zeigt wer Chef ist", emoji: "💪" },
    ],
    'it-IT': [
      { text: "Zeus è arrabbiato oggi", emoji: "⚡" },
      { text: "Thor fa festa lassù", emoji: "🔨" },
      { text: "Meglio restare a casa", emoji: "🏠" },
      { text: "Tempesta vera, non è uno scherzo", emoji: "🌩️" },
      { text: "Il cielo fa un concerto", emoji: "🎸" },
      { text: "Meglio non rischiare", emoji: "😰" },
      { text: "Modalità drammatica attivata", emoji: "⛈️" },
      { text: "La natura comanda", emoji: "💪" },
    ],
    'ja-JP': [
      { text: "今日はゼウス様お怒りモード", emoji: "⚡" },
      { text: "雷神様パーティー中", emoji: "🔨" },
      { text: "おうちにいるのが正解", emoji: "🏠" },
      { text: "本気の嵐だよ", emoji: "🌩️" },
      { text: "空がライブ中", emoji: "🎸" },
      { text: "外出は控えめに", emoji: "😰" },
      { text: "ドラマチックモード全開", emoji: "⛈️" },
      { text: "自然の力すごい", emoji: "💪" },
    ],
    'ko-KR': [
      { text: "제우스가 화났다", emoji: "⚡" },
      { text: "토르가 파티 중", emoji: "🔨" },
      { text: "집에 있는 게 정답", emoji: "🏠" },
      { text: "진짜 폭풍이야", emoji: "🌩️" },
      { text: "하늘이 콘서트 중", emoji: "🎸" },
      { text: "밖에 안 나가는 게 좋겠다", emoji: "😰" },
      { text: "드라마틱 모드 ON", emoji: "⛈️" },
      { text: "자연의 위엄", emoji: "💪" },
    ],
    'zh-CN': [
      { text: "雷公今天心情不好", emoji: "⚡" },
      { text: "电母在开派对", emoji: "🔨" },
      { text: "宅家才是王道", emoji: "🏠" },
      { text: "真正的暴风雨", emoji: "🌩️" },
      { text: "天空在开演唱会", emoji: "🎸" },
      { text: "还是别出门了", emoji: "😰" },
      { text: "戏剧模式全开", emoji: "⛈️" },
      { text: "大自然在秀肌肉", emoji: "💪" },
    ],
  },
  snow: {
    'pt-BR': [
      { text: "Elsa passou por aqui", emoji: "❄️" },
      { text: "Dia de chocolate quente e cobertas", emoji: "☕" },
      { text: "Parece cenário de filme", emoji: "🎬" },
      { text: "Branco demais, parece sonho", emoji: "✨" },
      { text: "Hora de fazer boneco de neve", emoji: "⛄" },
      { text: "Frozen na vida real", emoji: "👸" },
      { text: "Vista tudo que você tem", emoji: "🧣" },
      { text: "Paisagem de cartão de Natal", emoji: "🎄" },
    ],
    'en-US': [
      { text: "Elsa was here", emoji: "❄️" },
      { text: "Hot cocoa weather activated", emoji: "☕" },
      { text: "It's giving winter wonderland", emoji: "✨" },
      { text: "Snowball fight time!", emoji: "⛄" },
      { text: "Frozen vibes are real", emoji: "👸" },
      { text: "Layer up buttercup!", emoji: "🧣" },
      { text: "Christmas card aesthetic", emoji: "🎄" },
      { text: "Let it snow, let it snow", emoji: "🎵" },
    ],
    'es-ES': [
      { text: "Elsa pasó por aquí", emoji: "❄️" },
      { text: "Hora de chocolate caliente", emoji: "☕" },
      { text: "Parece una película", emoji: "🎬" },
      { text: "¡A hacer muñecos de nieve!", emoji: "⛄" },
      { text: "Frozen en la vida real", emoji: "👸" },
      { text: "Abrígate bien", emoji: "🧣" },
      { text: "Postal navideña", emoji: "🎄" },
      { text: "Blanco como la nieve", emoji: "✨" },
    ],
    'fr-FR': [
      { text: "Elsa est passée par là", emoji: "❄️" },
      { text: "L'heure du chocolat chaud", emoji: "☕" },
      { text: "On se croirait dans un film", emoji: "🎬" },
      { text: "Bataille de boules de neige!", emoji: "⛄" },
      { text: "Frozen dans la vraie vie", emoji: "👸" },
      { text: "Couvre-toi bien", emoji: "🧣" },
      { text: "Carte postale de Noël", emoji: "🎄" },
      { text: "Blanc comme neige", emoji: "✨" },
    ],
    'de-DE': [
      { text: "Elsa war hier", emoji: "❄️" },
      { text: "Zeit für heiße Schokolade", emoji: "☕" },
      { text: "Wie im Film", emoji: "🎬" },
      { text: "Schneeballschlacht!", emoji: "⛄" },
      { text: "Frozen im echten Leben", emoji: "👸" },
      { text: "Zieh dich warm an", emoji: "🧣" },
      { text: "Weihnachtskarten-Wetter", emoji: "🎄" },
      { text: "Winterwunderland", emoji: "✨" },
    ],
    'it-IT': [
      { text: "Elsa è passata di qui", emoji: "❄️" },
      { text: "Ora della cioccolata calda", emoji: "☕" },
      { text: "Sembra un film", emoji: "🎬" },
      { text: "Battaglia a palle di neve!", emoji: "⛄" },
      { text: "Frozen nella vita reale", emoji: "👸" },
      { text: "Copriti bene", emoji: "🧣" },
      { text: "Cartolina di Natale", emoji: "🎄" },
      { text: "Bianco come la neve", emoji: "✨" },
    ],
    'ja-JP': [
      { text: "エルサが来たみたい", emoji: "❄️" },
      { text: "ホットココアの季節", emoji: "☕" },
      { text: "映画みたいな景色", emoji: "🎬" },
      { text: "雪だるま作ろう！", emoji: "⛄" },
      { text: "リアルアナ雪", emoji: "👸" },
      { text: "暖かくしてね", emoji: "🧣" },
      { text: "クリスマスカードみたい", emoji: "🎄" },
      { text: "銀世界だね〜", emoji: "✨" },
    ],
    'ko-KR': [
      { text: "엘사가 다녀갔나봐", emoji: "❄️" },
      { text: "핫초코 마실 시간", emoji: "☕" },
      { text: "영화 같은 풍경", emoji: "🎬" },
      { text: "눈사람 만들자!", emoji: "⛄" },
      { text: "리얼 겨울왕국", emoji: "👸" },
      { text: "따뜻하게 입어", emoji: "🧣" },
      { text: "크리스마스 카드 같아", emoji: "🎄" },
      { text: "눈의 나라", emoji: "✨" },
    ],
    'zh-CN': [
      { text: "艾莎来过了", emoji: "❄️" },
      { text: "热可可时间到", emoji: "☕" },
      { text: "像电影一样美", emoji: "🎬" },
      { text: "打雪仗去！", emoji: "⛄" },
      { text: "真实版冰雪奇缘", emoji: "👸" },
      { text: "穿暖和点", emoji: "🧣" },
      { text: "圣诞贺卡既视感", emoji: "🎄" },
      { text: "银装素裹", emoji: "✨" },
    ],
  },
  fog: {
    'pt-BR': [
      { text: "Silent Hill vibes", emoji: "🌫️" },
      { text: "A neblina engoliu a cidade", emoji: "😶‍🌫️" },
      { text: "Dia misterioso hoje", emoji: "🔮" },
      { text: "Parece filme de terror", emoji: "👻" },
      { text: "Dirija com cuidado!", emoji: "🚗" },
      { text: "A cidade sumiu", emoji: "🌫️" },
      { text: "Clima de mistério", emoji: "🕵️" },
      { text: "Visibilidade zero, paciência mil", emoji: "😌" },
    ],
    'en-US': [
      { text: "Silent Hill mode activated", emoji: "🌫️" },
      { text: "The fog ate the city", emoji: "😶‍🌫️" },
      { text: "Mysterious vibes today", emoji: "🔮" },
      { text: "Horror movie aesthetic", emoji: "👻" },
      { text: "Drive carefully!", emoji: "🚗" },
      { text: "The city disappeared", emoji: "🌫️" },
      { text: "Mystery atmosphere", emoji: "🕵️" },
      { text: "Visibility? What visibility?", emoji: "😅" },
    ],
    'es-ES': [
      { text: "Modo Silent Hill activado", emoji: "🌫️" },
      { text: "La niebla se tragó la ciudad", emoji: "😶‍🌫️" },
      { text: "Día misterioso", emoji: "🔮" },
      { text: "Estética de película de terror", emoji: "👻" },
      { text: "¡Conduce con cuidado!", emoji: "🚗" },
      { text: "La ciudad desapareció", emoji: "🌫️" },
      { text: "Atmósfera de misterio", emoji: "🕵️" },
      { text: "¿Visibilidad? ¿Qué es eso?", emoji: "😅" },
    ],
    'fr-FR': [
      { text: "Mode Silent Hill activé", emoji: "🌫️" },
      { text: "Le brouillard a mangé la ville", emoji: "😶‍🌫️" },
      { text: "Journée mystérieuse", emoji: "🔮" },
      { text: "Esthétique film d'horreur", emoji: "👻" },
      { text: "Conduis prudemment!", emoji: "🚗" },
      { text: "La ville a disparu", emoji: "🌫️" },
      { text: "Atmosphère de mystère", emoji: "🕵️" },
      { text: "Visibilité? Quelle visibilité?", emoji: "😅" },
    ],
    'de-DE': [
      { text: "Silent Hill Modus aktiviert", emoji: "🌫️" },
      { text: "Der Nebel hat die Stadt verschluckt", emoji: "😶‍🌫️" },
      { text: "Mysteriöser Tag", emoji: "🔮" },
      { text: "Horrorfilm-Ästhetik", emoji: "👻" },
      { text: "Fahr vorsichtig!", emoji: "🚗" },
      { text: "Die Stadt ist verschwunden", emoji: "🌫️" },
      { text: "Mysteriöse Atmosphäre", emoji: "🕵️" },
      { text: "Sichtweite? Was ist das?", emoji: "😅" },
    ],
    'it-IT': [
      { text: "Modalità Silent Hill attivata", emoji: "🌫️" },
      { text: "La nebbia ha mangiato la città", emoji: "😶‍🌫️" },
      { text: "Giornata misteriosa", emoji: "🔮" },
      { text: "Estetica da film horror", emoji: "👻" },
      { text: "Guida con prudenza!", emoji: "🚗" },
      { text: "La città è scomparsa", emoji: "🌫️" },
      { text: "Atmosfera di mistero", emoji: "🕵️" },
      { text: "Visibilità? Che cos'è?", emoji: "😅" },
    ],
    'ja-JP': [
      { text: "サイレントヒルモード", emoji: "🌫️" },
      { text: "霧が街を飲み込んだ", emoji: "😶‍🌫️" },
      { text: "ミステリアスな一日", emoji: "🔮" },
      { text: "ホラー映画みたい", emoji: "👻" },
      { text: "運転気をつけて！", emoji: "🚗" },
      { text: "街が消えた", emoji: "🌫️" },
      { text: "ミステリーな雰囲気", emoji: "🕵️" },
      { text: "視界ゼロ〜", emoji: "😅" },
    ],
    'ko-KR': [
      { text: "사일런트 힐 모드", emoji: "🌫️" },
      { text: "안개가 도시를 삼켰다", emoji: "😶‍🌫️" },
      { text: "미스터리한 하루", emoji: "🔮" },
      { text: "공포영화 분위기", emoji: "👻" },
      { text: "운전 조심해!", emoji: "🚗" },
      { text: "도시가 사라졌다", emoji: "🌫️" },
      { text: "미스터리 분위기", emoji: "🕵️" },
      { text: "시야? 그게 뭐야?", emoji: "😅" },
    ],
    'zh-CN': [
      { text: "寂静岭模式开启", emoji: "🌫️" },
      { text: "雾霾吞噬了城市", emoji: "😶‍🌫️" },
      { text: "神秘的一天", emoji: "🔮" },
      { text: "恐怖片既视感", emoji: "👻" },
      { text: "开车小心！", emoji: "🚗" },
      { text: "城市消失了", emoji: "🌫️" },
      { text: "神秘氛围", emoji: "🕵️" },
      { text: "能见度？那是什么？", emoji: "😅" },
    ],
  },
  cold: {
    'pt-BR': [
      { text: "Pega a coberta e corre pra cama!", emoji: "🥶" },
      { text: "Dia de sopinha e Netflix", emoji: "🍲" },
      { text: "Frio de rachar o coco", emoji: "❄️" },
      { text: "Cobertor é meu melhor amigo", emoji: "🛏️" },
      { text: "Vim pro trabalho, mas queria a cama", emoji: "😴" },
      { text: "Chocolate quente urgente!", emoji: "☕" },
      { text: "Frio que congela até pensamento", emoji: "🧊" },
      { text: "Perfeito pra fondue!", emoji: "🫕" },
    ],
    'en-US': [
      { text: "Blanket burrito weather", emoji: "🌯" },
      { text: "Soup and Netflix kinda day", emoji: "🍲" },
      { text: "Freezing cold, send help", emoji: "🥶" },
      { text: "My blanket is my bestie today", emoji: "🛏️" },
      { text: "Wish I could WFB (work from bed)", emoji: "😴" },
      { text: "Hot cocoa ASAP!", emoji: "☕" },
      { text: "Cold enough to freeze thoughts", emoji: "🧊" },
      { text: "Perfect fondue weather", emoji: "🫕" },
    ],
    'es-ES': [
      { text: "Día de manta y sofá", emoji: "🛋️" },
      { text: "Sopita y Netflix", emoji: "🍲" },
      { text: "Frío que pela", emoji: "🥶" },
      { text: "Mi manta es mi mejor amiga", emoji: "🛏️" },
      { text: "Quiero quedarme en la cama", emoji: "😴" },
      { text: "¡Chocolate caliente urgente!", emoji: "☕" },
      { text: "Frío que congela", emoji: "🧊" },
      { text: "Perfecto para fondue", emoji: "🫕" },
    ],
    'fr-FR': [
      { text: "Journée plaid et canapé", emoji: "🛋️" },
      { text: "Soupe et Netflix", emoji: "🍲" },
      { text: "Froid de canard", emoji: "🥶" },
      { text: "Ma couverture est ma meilleure amie", emoji: "🛏️" },
      { text: "J'aurais voulu rester au lit", emoji: "😴" },
      { text: "Chocolat chaud d'urgence!", emoji: "☕" },
      { text: "Il gèle!", emoji: "🧊" },
      { text: "Parfait pour une fondue", emoji: "🫕" },
    ],
    'de-DE': [
      { text: "Decke und Sofa-Tag", emoji: "🛋️" },
      { text: "Suppe und Netflix", emoji: "🍲" },
      { text: "Arschkalt heute", emoji: "🥶" },
      { text: "Meine Decke ist mein BFF", emoji: "🛏️" },
      { text: "Wäre lieber im Bett geblieben", emoji: "😴" },
      { text: "Heiße Schokolade sofort!", emoji: "☕" },
      { text: "Es friert!", emoji: "🧊" },
      { text: "Perfekt für Fondue", emoji: "🫕" },
    ],
    'it-IT': [
      { text: "Giornata coperta e divano", emoji: "🛋️" },
      { text: "Zuppa e Netflix", emoji: "🍲" },
      { text: "Freddo cane", emoji: "🥶" },
      { text: "La mia coperta è la mia migliore amica", emoji: "🛏️" },
      { text: "Vorrei essere ancora a letto", emoji: "😴" },
      { text: "Cioccolata calda urgente!", emoji: "☕" },
      { text: "Si gela!", emoji: "🧊" },
      { text: "Perfetto per la fonduta", emoji: "🫕" },
    ],
    'ja-JP': [
      { text: "こたつから出られない日だね〜", emoji: "🍊" },
      { text: "お鍋とネットフリックス", emoji: "🍲" },
      { text: "めちゃくちゃ寒い", emoji: "🥶" },
      { text: "お布団が恋しい...", emoji: "🛏️" },
      { text: "ベッドから出たくない", emoji: "😴" },
      { text: "ホットココア緊急！", emoji: "☕" },
      { text: "凍える寒さ", emoji: "🧊" },
      { text: "鍋パーティーの季節！", emoji: "🫕" },
    ],
    'ko-KR': [
      { text: "이불 밖은 위험해", emoji: "🛏️" },
      { text: "국물 + 넷플릭스", emoji: "🍲" },
      { text: "진짜 춥다", emoji: "🥶" },
      { text: "이불이 최고야", emoji: "😴" },
      { text: "침대에서 나오기 싫어", emoji: "😴" },
      { text: "핫초코 긴급!", emoji: "☕" },
      { text: "얼어붙는 추위", emoji: "🧊" },
      { text: "샤브샤브 날씨", emoji: "🫕" },
    ],
    'zh-CN': [
      { text: "被窝才是真爱", emoji: "🛏️" },
      { text: "热汤+追剧", emoji: "🍲" },
      { text: "冷到怀疑人生", emoji: "🥶" },
      { text: "被子是最好的朋友", emoji: "😴" },
      { text: "不想离开床", emoji: "😴" },
      { text: "热可可紧急需要！", emoji: "☕" },
      { text: "冻成狗", emoji: "🧊" },
      { text: "火锅走起！", emoji: "🫕" },
    ],
  },
  windy: {
    'pt-BR': [
      { text: "Ventando mais que boca de político", emoji: "💨" },
      { text: "Cabelo? Que cabelo?", emoji: "💇" },
      { text: "Segura o boné!", emoji: "🧢" },
      { text: "Dia de empinar pipa", emoji: "🪁" },
      { text: "O vento tá furioso", emoji: "🌬️" },
      { text: "Cuidado com os guarda-chuvas voadores", emoji: "☂️" },
      { text: "Praia? Só se for pra virar sanduíche de areia", emoji: "🏖️" },
      { text: "Parece um secador de cabelo gigante", emoji: "💨" },
    ],
    'en-US': [
      { text: "Hair? What hair?", emoji: "💇" },
      { text: "Hold onto your hat!", emoji: "🧢" },
      { text: "Perfect kite flying weather", emoji: "🪁" },
      { text: "The wind chose chaos today", emoji: "🌬️" },
      { text: "Flying umbrella alert", emoji: "☂️" },
      { text: "It's giving wind tunnel vibes", emoji: "💨" },
      { text: "My hair has its own plans", emoji: "💇‍♀️" },
      { text: "Nature's blow dryer activated", emoji: "💨" },
    ],
    'es-ES': [
      { text: "¿Pelo? ¿Qué pelo?", emoji: "💇" },
      { text: "¡Sujeta el sombrero!", emoji: "🧢" },
      { text: "Perfecto para volar cometas", emoji: "🪁" },
      { text: "El viento está loco hoy", emoji: "🌬️" },
      { text: "Alerta de paraguas voladores", emoji: "☂️" },
      { text: "Viento de locos", emoji: "💨" },
      { text: "Mi pelo tiene vida propia", emoji: "💇‍♀️" },
      { text: "Secador natural activado", emoji: "💨" },
    ],
    'fr-FR': [
      { text: "Cheveux? Quels cheveux?", emoji: "💇" },
      { text: "Tiens ton chapeau!", emoji: "🧢" },
      { text: "Parfait pour le cerf-volant", emoji: "🪁" },
      { text: "Le vent est fou aujourd'hui", emoji: "🌬️" },
      { text: "Alerte parapluies volants", emoji: "☂️" },
      { text: "Vent de dingue", emoji: "💨" },
      { text: "Mes cheveux ont leur propre plan", emoji: "💇‍♀️" },
      { text: "Sèche-cheveux naturel activé", emoji: "💨" },
    ],
    'de-DE': [
      { text: "Haare? Welche Haare?", emoji: "💇" },
      { text: "Halt deinen Hut fest!", emoji: "🧢" },
      { text: "Perfekt zum Drachen steigen", emoji: "🪁" },
      { text: "Der Wind ist verrückt heute", emoji: "🌬️" },
      { text: "Fliegende Regenschirme-Alarm", emoji: "☂️" },
      { text: "Verrückter Wind", emoji: "💨" },
      { text: "Meine Haare machen was sie wollen", emoji: "💇‍♀️" },
      { text: "Natürlicher Föhn aktiviert", emoji: "💨" },
    ],
    'it-IT': [
      { text: "Capelli? Quali capelli?", emoji: "💇" },
      { text: "Tieni il cappello!", emoji: "🧢" },
      { text: "Perfetto per gli aquiloni", emoji: "🪁" },
      { text: "Il vento è pazzo oggi", emoji: "🌬️" },
      { text: "Allarme ombrelli volanti", emoji: "☂️" },
      { text: "Vento da pazzi", emoji: "💨" },
      { text: "I miei capelli hanno piani propri", emoji: "💇‍♀️" },
      { text: "Asciugacapelli naturale attivato", emoji: "💨" },
    ],
    'ja-JP': [
      { text: "髪？何それ？", emoji: "💇" },
      { text: "帽子飛ばされないように！", emoji: "🧢" },
      { text: "凧揚げ日和", emoji: "🪁" },
      { text: "風が暴れてる", emoji: "🌬️" },
      { text: "傘が飛ぶかも", emoji: "☂️" },
      { text: "すごい風だね", emoji: "💨" },
      { text: "髪型が終わった", emoji: "💇‍♀️" },
      { text: "天然ドライヤー", emoji: "💨" },
    ],
    'ko-KR': [
      { text: "머리? 무슨 머리?", emoji: "💇" },
      { text: "모자 꽉 잡아!", emoji: "🧢" },
      { text: "연 날리기 좋은 날", emoji: "🪁" },
      { text: "바람이 미쳤어", emoji: "🌬️" },
      { text: "우산 날아갈 수도", emoji: "☂️" },
      { text: "바람 진짜 세다", emoji: "💨" },
      { text: "머리 스타일 망함", emoji: "💇‍♀️" },
      { text: "천연 드라이어", emoji: "💨" },
    ],
    'zh-CN': [
      { text: "头发？什么头发？", emoji: "💇" },
      { text: "抓紧你的帽子！", emoji: "🧢" },
      { text: "放风筝的好日子", emoji: "🪁" },
      { text: "风今天疯了", emoji: "🌬️" },
      { text: "小心飞走的雨伞", emoji: "☂️" },
      { text: "风超级大", emoji: "💨" },
      { text: "发型全毁了", emoji: "💇‍♀️" },
      { text: "天然吹风机", emoji: "💨" },
    ],
  },
};

// Get a random phrase for a given category and language
export function getRandomPhrase(category: WeatherCategory, language: string): WeatherPhrase {
  const lang = (language as SupportedLanguage) || 'en-US';
  const categoryPhrases = phrases[category]?.[lang] || phrases[category]?.['en-US'] || [];
  
  if (categoryPhrases.length === 0) {
    return { text: "Enjoy your day!", emoji: "☀️" };
  }
  
  const randomIndex = Math.floor(Math.random() * categoryPhrases.length);
  return categoryPhrases[randomIndex];
}

// Get phrase based on weather code, temperature and language
export function getWeatherPhrase(weatherCode: number, temperature: number, language: string): WeatherPhrase {
  const category = getWeatherCategory(weatherCode, temperature);
  return getRandomPhrase(category, language);
}

// Cache key for localStorage
export function getPhrasesCacheKey(weatherCode: number, temperature: number, language: string): string {
  const category = getWeatherCategory(weatherCode, temperature);
  return `weather_phrase_${category}_${language}`;
}
