import { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { ptBR, enUS, es, fr, de, it, ja, ko, zhCN, Locale } from "date-fns/locale";
import { supabase } from "@/integrations/supabase/client";

export type LanguageCode = 'pt-BR' | 'en-US' | 'es-ES' | 'fr-FR' | 'de-DE' | 'it-IT' | 'ja-JP' | 'ko-KR' | 'zh-CN';

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
  getDateLocale: () => Locale;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Date-fns locale mapping
const DATE_LOCALES: Record<LanguageCode, Locale> = {
  'pt-BR': ptBR,
  'en-US': enUS,
  'es-ES': es,
  'fr-FR': fr,
  'de-DE': de,
  'it-IT': it,
  'ja-JP': ja,
  'ko-KR': ko,
  'zh-CN': zhCN,
};

// Translations
const translations: Record<LanguageCode, Record<string, string>> = {
  'pt-BR': {
    // Navigation
    'nav.chat': 'Chat',
    'nav.list': 'Lista',
    'nav.calendar': 'Calendário',
    
    // Common
    'common.back': 'Voltar',
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.delete': 'Excluir',
    'common.edit': 'Editar',
    'common.search': 'Buscar',
    'common.loading': 'Carregando...',
    'common.today': 'Hoje',
    'common.tomorrow': 'Amanhã',
    'common.yesterday': 'Ontem',
    
    // Settings
    'settings.title': 'Configurações',
    'settings.myPlan': 'Meu plano',
    'settings.calendars': 'Calendários',
    'settings.notifications': 'Notificações',
    'settings.smartTasks': 'Ações Inteligentes',
    'settings.specialFeatures': 'Recursos Premium',
    'settings.account': 'Conta',
    'settings.appearance': 'Aparência',
    'settings.language': 'Idioma',
    'settings.feedback': 'Comentários',
    'settings.about': 'Sobre',
    'settings.logout': 'Sair',
    'settings.kairo': 'HORAH',
    'settings.general': 'GERAL',
    'settings.others': 'OUTROS',
    'settings.system': 'Sistema',
    
    // Language page
    'language.title': 'Idioma',
    'language.search': 'Buscar idioma...',
    'language.note': 'O idioma será aplicado a toda a interface do Horah. Algumas traduções podem estar incompletas.',
    
    // My Plan page
    'plan.title': 'Meu plano',
    'plan.free': 'Grátis',
    'plan.plus': 'PLUS',
    'plan.super': 'SUPER',
    'plan.premium': 'Planos Horah Premium',
    'plan.tryFree': 'Experimente grátis por 7 dias',
    'plan.eventsScheduled': 'Eventos agendados',
    'plan.upgradeNow': 'Atualizar agora',
    'plan.monthly': 'Mensal',
    'plan.yearly': 'Anual',
    'plan.saveYearly': 'Economize 17% com a cobrança anual',
    'plan.features': 'Recursos Premium',
    'plan.faq': 'Perguntas e Respostas',
    'plan.terms': 'Termos de Serviço',
    'plan.privacy': 'Política de Privacidade',
    'plan.manageSubscription': 'Gerenciar assinatura e pagamentos',
    'plan.restorePurchases': 'Restaurar compras',
    'plan.manage': 'Gerenciar',
    
    // Appearance
    'appearance.light': 'Claro',
    'appearance.dark': 'Escuro',
    
    // Chat
    'chat.placeholder': 'Escreva uma mensagem...',
    'chat.greeting': 'E aí! O que vamos agendar hoje?',
    'chat.today': 'Hoje',
    'chat.yesterday': 'Ontem',
    'chat.errorConnect': 'Falha ao conectar com a IA',
    'chat.viewFullHistory': 'Ver todo o histórico',
    'chat.startOfConversation': 'Início da conversa',
    'chat.suggestion1': 'Organizar um churrasco com os amigos neste sábado às 13h.',
    'chat.suggestion2': 'Consulta médica na quarta-feira às 9h.',
    'chat.suggestion3': 'Café com a Sofia amanhã às 16h na padaria.',
    'chat.suggestion4': 'Comprar ingressos para o jogo neste fim de semana.',
    
    // Calendar
    'calendar.today': 'Hoje',
    'calendar.tomorrow': 'Amanhã',
    'calendar.noEvents': 'Nenhum evento',
    'calendar.todayIs': 'hoje é dia',
    'calendar.allDay': 'Dia inteiro',
    'calendar.weekdaySun': 'D',
    'calendar.weekdayMon': 'S',
    'calendar.weekdayTue': 'T',
    'calendar.weekdayWed': 'Q',
    'calendar.weekdayThu': 'Q',
    'calendar.weekdayFri': 'S',
    'calendar.weekdaySat': 'S',
    
    // About
    'about.title': 'Sobre',
    'about.terms': 'Termos de Serviço',
    'about.privacy': 'Política de Privacidade',
    'about.faq': 'Perguntas Frequentes',
    'about.version': 'Versão',
    
    // Events
    'event.created': 'Evento Criado',
    'event.updated': 'Evento Atualizado',
    'event.deleted': 'Evento Removido',
    'event.completed': 'Evento Realizado',
    'event.callMe': 'Me Ligue',
    'event.allDay': 'Dia inteiro',
    'event.pastDate': 'Data no passado',
    'event.pastDateMessage': 'Essa data e horário já passaram. O evento foi criado, mas não será possível enviar lembretes.',
    'event.tooClose': 'muito próximo',
    'event.eventAdded': 'O Evento Foi Adicionado',
    'event.reminder': 'antes',
    'event.oneHourBefore': '1 hora antes',
    
    // Onboarding
    'onboarding.welcome': 'Olá! Sou o Horah, seu assistente pessoal de agenda. 📅\n\nMe conte sobre um evento que você gostaria de agendar e eu cuido do resto!',
    'onboarding.firstEventSuccess': 'Perfeito! 🎉 Seu primeiro evento foi criado com sucesso.\n\nAgora você pode continuar me contando sobre seus compromissos, e eu vou organizando tudo pra você!',
  },
  'en-US': {
    // Navigation
    'nav.chat': 'Chat',
    'nav.list': 'List',
    'nav.calendar': 'Calendar',
    
    // Common
    'common.back': 'Back',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.search': 'Search',
    'common.loading': 'Loading...',
    'common.today': 'Today',
    'common.tomorrow': 'Tomorrow',
    'common.yesterday': 'Yesterday',
    
    // Settings
    'settings.title': 'Settings',
    'settings.myPlan': 'My Plan',
    'settings.calendars': 'Calendars',
    'settings.notifications': 'Notifications',
    'settings.smartTasks': 'Smart Tasks',
    'settings.specialFeatures': 'Special Features',
    'settings.account': 'Account',
    'settings.appearance': 'Appearance',
    'settings.language': 'Language',
    'settings.feedback': 'Feedback',
    'settings.about': 'About',
    'settings.logout': 'Log out',
    'settings.kairo': 'HORAH',
    'settings.general': 'GENERAL',
    'settings.others': 'OTHERS',
    'settings.system': 'System',
    
    // Language page
    'language.title': 'Language',
    'language.search': 'Search language...',
    'language.note': 'The language will be applied to the entire Horah interface. Some translations may be incomplete.',
    
    // My Plan page
    'plan.title': 'My Plan',
    'plan.free': 'Free',
    'plan.plus': 'PLUS',
    'plan.super': 'SUPER',
    'plan.premium': 'Horah Premium Plans',
    'plan.tryFree': 'Try free for 7 days',
    'plan.eventsScheduled': 'Events scheduled',
    'plan.upgradeNow': 'Upgrade now',
    'plan.monthly': 'Monthly',
    'plan.yearly': 'Yearly',
    'plan.saveYearly': 'Save 17% with annual billing',
    'plan.features': 'Premium Features',
    'plan.faq': 'Questions and Answers',
    'plan.terms': 'Terms of Service',
    'plan.privacy': 'Privacy Policy',
    'plan.manageSubscription': 'Manage subscription and payments',
    'plan.restorePurchases': 'Restore purchases',
    'plan.manage': 'Manage',
    
    // Appearance
    'appearance.light': 'Light',
    'appearance.dark': 'Dark',
    
    // Chat
    'chat.placeholder': 'Write a message...',
    'chat.greeting': 'Hey! What shall we schedule today?',
    'chat.today': 'Today',
    'chat.yesterday': 'Yesterday',
    'chat.errorConnect': 'Failed to connect to AI',
    'chat.viewFullHistory': 'View full history',
    'chat.startOfConversation': 'Start of conversation',
    'chat.suggestion1': 'Organize a barbecue with friends this Saturday at 1pm.',
    'chat.suggestion2': 'Doctor appointment on Wednesday at 9am.',
    'chat.suggestion3': 'Coffee with Sofia tomorrow at 4pm at the bakery.',
    'chat.suggestion4': 'Buy tickets for the game this weekend.',
    
    // Calendar
    'calendar.today': 'Today',
    'calendar.tomorrow': 'Tomorrow',
    'calendar.noEvents': 'No events',
    'calendar.todayIs': 'today is',
    'calendar.allDay': 'All day',
    'calendar.weekdaySun': 'S',
    'calendar.weekdayMon': 'M',
    'calendar.weekdayTue': 'T',
    'calendar.weekdayWed': 'W',
    'calendar.weekdayThu': 'T',
    'calendar.weekdayFri': 'F',
    'calendar.weekdaySat': 'S',
    
    // About
    'about.title': 'About',
    'about.terms': 'Terms of Service',
    'about.privacy': 'Privacy Policy',
    'about.faq': 'Frequently Asked Questions',
    'about.version': 'Version',
    
    // Events
    'event.created': 'Event Created',
    'event.updated': 'Event Updated',
    'event.deleted': 'Event Deleted',
    'event.completed': 'Event Completed',
    'event.callMe': 'Call Me',
    'event.allDay': 'All day',
    'event.pastDate': 'Past date',
    'event.pastDateMessage': 'This date and time have already passed. The event was created, but reminders cannot be sent.',
    'event.tooClose': 'too close',
    'event.eventAdded': 'Event Added',
    'event.reminder': 'before',
    'event.oneHourBefore': '1 hour before',
    
    // Onboarding
    'onboarding.welcome': 'Hi! I\'m Horah, your personal calendar assistant. 📅\n\nTell me about an event you\'d like to schedule and I\'ll take care of the rest!',
    'onboarding.firstEventSuccess': 'Perfect! 🎉 Your first event was created successfully.\n\nNow you can keep telling me about your appointments, and I\'ll organize everything for you!',
  },
  'es-ES': {
    // Navigation
    'nav.chat': 'Chat',
    'nav.list': 'Lista',
    'nav.calendar': 'Calendario',
    
    // Common
    'common.back': 'Volver',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.search': 'Buscar',
    'common.loading': 'Cargando...',
    'common.today': 'Hoy',
    'common.tomorrow': 'Mañana',
    'common.yesterday': 'Ayer',
    
    // Settings
    'settings.title': 'Configuración',
    'settings.myPlan': 'Mi plan',
    'settings.calendars': 'Calendarios',
    'settings.notifications': 'Notificaciones',
    'settings.smartTasks': 'Tareas Inteligentes',
    'settings.specialFeatures': 'Funciones Especiales',
    'settings.account': 'Cuenta',
    'settings.appearance': 'Apariencia',
    'settings.language': 'Idioma',
    'settings.feedback': 'Comentarios',
    'settings.about': 'Acerca de',
    'settings.logout': 'Cerrar sesión',
    'settings.kairo': 'HORAH',
    'settings.general': 'GENERAL',
    'settings.others': 'OTROS',
    'settings.system': 'Sistema',
    
    // Language page
    'language.title': 'Idioma',
    'language.search': 'Buscar idioma...',
    'language.note': 'El idioma se aplicará a toda la interfaz de Horah. Algunas traducciones pueden estar incompletas.',
    
    // My Plan page
    'plan.title': 'Mi plan',
    'plan.free': 'Gratis',
    'plan.plus': 'PLUS',
    'plan.super': 'SUPER',
    'plan.premium': 'Planes Horah Premium',
    'plan.tryFree': 'Prueba gratis por 7 días',
    'plan.eventsScheduled': 'Eventos programados',
    'plan.upgradeNow': 'Actualizar ahora',
    'plan.monthly': 'Mensual',
    'plan.yearly': 'Anual',
    'plan.saveYearly': 'Ahorra 17% con facturación anual',
    'plan.features': 'Funciones Premium',
    'plan.faq': 'Preguntas y Respuestas',
    'plan.terms': 'Términos de Servicio',
    'plan.privacy': 'Política de Privacidad',
    'plan.manageSubscription': 'Gestionar suscripción y pagos',
    'plan.restorePurchases': 'Restaurar compras',
    'plan.manage': 'Gestionar',
    
    // Appearance
    'appearance.light': 'Claro',
    'appearance.dark': 'Oscuro',
    
    // Chat
    'chat.placeholder': 'Escribe un mensaje...',
    'chat.greeting': '¡Hola! ¿Qué vamos a agendar hoy?',
    'chat.today': 'Hoy',
    'chat.yesterday': 'Ayer',
    'chat.errorConnect': 'Error al conectar con la IA',
    'chat.viewFullHistory': 'Ver historial completo',
    'chat.startOfConversation': 'Inicio de la conversación',
    'chat.suggestion1': 'Organizar una parrillada con amigos este sábado a las 13h.',
    'chat.suggestion2': 'Cita médica el miércoles a las 9h.',
    'chat.suggestion3': 'Café con Sofía mañana a las 16h en la panadería.',
    'chat.suggestion4': 'Comprar entradas para el partido este fin de semana.',
    
    // Calendar
    'calendar.today': 'Hoy',
    'calendar.tomorrow': 'Mañana',
    'calendar.noEvents': 'Sin eventos',
    'calendar.todayIs': 'hoy es',
    'calendar.allDay': 'Todo el día',
    'calendar.weekdaySun': 'D',
    'calendar.weekdayMon': 'L',
    'calendar.weekdayTue': 'M',
    'calendar.weekdayWed': 'X',
    'calendar.weekdayThu': 'J',
    'calendar.weekdayFri': 'V',
    'calendar.weekdaySat': 'S',
    
    // About
    'about.title': 'Acerca de',
    'about.terms': 'Términos de Servicio',
    'about.privacy': 'Política de Privacidad',
    'about.faq': 'Preguntas Frecuentes',
    'about.version': 'Versión',
    
    // Events
    'event.created': 'Evento Creado',
    'event.updated': 'Evento Actualizado',
    'event.deleted': 'Evento Eliminado',
    'event.completed': 'Evento Realizado',
    'event.callMe': 'Llámame',
    'event.allDay': 'Todo el día',
    'event.pastDate': 'Fecha pasada',
    'event.pastDateMessage': 'Esta fecha y hora ya pasaron. El evento fue creado, pero no será posible enviar recordatorios.',
    'event.tooClose': 'muy próximo',
    'event.eventAdded': 'Evento Agregado',
    'event.reminder': 'antes',
    'event.oneHourBefore': '1 hora antes',
    
    // Onboarding
    'onboarding.welcome': '¡Hola! Soy Horah, tu asistente personal de agenda. 📅\n\nCuéntame sobre un evento que te gustaría agendar y yo me encargo del resto!',
    'onboarding.firstEventSuccess': '¡Perfecto! 🎉 Tu primer evento fue creado con éxito.\n\nAhora puedes seguir contándome sobre tus compromisos, y yo organizaré todo para ti!',
  },
  'fr-FR': {
    'nav.chat': 'Chat',
    'nav.list': 'Liste',
    'nav.calendar': 'Calendrier',
    'common.back': 'Retour',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.confirm': 'Confirmer',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.search': 'Rechercher',
    'common.loading': 'Chargement...',
    'common.today': 'Aujourd\'hui',
    'common.tomorrow': 'Demain',
    'common.yesterday': 'Hier',
    'settings.title': 'Paramètres',
    'settings.myPlan': 'Mon forfait',
    'settings.calendars': 'Calendriers',
    'settings.notifications': 'Notifications',
    'settings.smartTasks': 'Tâches Intelligentes',
    'settings.specialFeatures': 'Fonctionnalités Spéciales',
    'settings.account': 'Compte',
    'settings.appearance': 'Apparence',
    'settings.language': 'Langue',
    'settings.feedback': 'Commentaires',
    'settings.about': 'À propos',
    'settings.logout': 'Déconnexion',
    'settings.kairo': 'HORAH',
    'settings.general': 'GÉNÉRAL',
    'settings.others': 'AUTRES',
    'settings.system': 'Système',
    'language.title': 'Langue',
    'language.search': 'Rechercher une langue...',
    'language.note': 'La langue sera appliquée à toute l\'interface Horah.',
    'plan.title': 'Mon forfait',
    'plan.free': 'Gratuit',
    'plan.plus': 'PLUS',
    'plan.super': 'SUPER',
    'plan.premium': 'Plans Horah Premium',
    'plan.tryFree': 'Essayez gratuitement pendant 7 jours',
    'plan.eventsScheduled': 'Événements programmés',
    'plan.upgradeNow': 'Mettre à niveau',
    'plan.monthly': 'Mensuel',
    'plan.yearly': 'Annuel',
    'plan.saveYearly': 'Économisez 17% avec la facturation annuelle',
    'plan.features': 'Fonctionnalités Premium',
    'plan.faq': 'Questions et Réponses',
    'plan.terms': 'Conditions d\'utilisation',
    'plan.privacy': 'Politique de confidentialité',
    'plan.manageSubscription': "Gérer l'abonnement et les paiements",
    'plan.restorePurchases': 'Restaurer les achats',
    'plan.manage': 'Gérer',
    'appearance.light': 'Clair',
    'appearance.dark': 'Sombre',
    'chat.placeholder': 'Écrivez un message...',
    'chat.greeting': 'Salut ! Qu\'est-ce qu\'on programme aujourd\'hui ?',
    'chat.today': 'Aujourd\'hui',
    'chat.yesterday': 'Hier',
    'chat.errorConnect': 'Échec de la connexion à l\'IA',
    'chat.viewFullHistory': 'Voir l\'historique complet',
    'chat.startOfConversation': 'Début de la conversation',
    'chat.suggestion1': 'Organiser un barbecue avec des amis ce samedi à 13h.',
    'chat.suggestion2': 'Rendez-vous médical mercredi à 9h.',
    'chat.suggestion3': 'Café avec Sofia demain à 16h à la boulangerie.',
    'chat.suggestion4': 'Acheter des billets pour le match ce week-end.',
    'calendar.today': 'Aujourd\'hui',
    'calendar.tomorrow': 'Demain',
    'calendar.noEvents': 'Aucun événement',
    'calendar.todayIs': 'aujourd\'hui c\'est le',
    'calendar.allDay': 'Toute la journée',
    'calendar.weekdaySun': 'D',
    'calendar.weekdayMon': 'L',
    'calendar.weekdayTue': 'M',
    'calendar.weekdayWed': 'M',
    'calendar.weekdayThu': 'J',
    'calendar.weekdayFri': 'V',
    'calendar.weekdaySat': 'S',
    'about.title': 'À propos',
    'about.terms': 'Conditions d\'utilisation',
    'about.privacy': 'Politique de confidentialité',
    'about.faq': 'Questions fréquentes',
    'about.version': 'Version',
    // Events
    'event.created': 'Événement Créé',
    'event.updated': 'Événement Mis à jour',
    'event.deleted': 'Événement Supprimé',
    'event.completed': 'Événement Réalisé',
    'event.callMe': 'Appelez-moi',
    'event.allDay': 'Toute la journée',
    'event.pastDate': 'Date passée',
    'event.pastDateMessage': 'Cette date et heure sont déjà passées. L\'événement a été créé, mais il ne sera pas possible d\'envoyer des rappels.',
    'event.tooClose': 'très proche',
    'event.eventAdded': 'Événement Ajouté',
    'event.reminder': 'avant',
    'event.oneHourBefore': '1 heure avant',
    // Onboarding
    'onboarding.welcome': 'Salut ! Je suis Horah, votre assistant personnel d\'agenda. 📅\n\nDites-moi quel événement vous aimeriez planifier et je m\'occupe du reste !',
    'onboarding.firstEventSuccess': 'Parfait ! 🎉 Votre premier événement a été créé avec succès.\n\nVous pouvez maintenant continuer à me parler de vos rendez-vous, et j\'organiserai tout pour vous !',
  },
  'de-DE': {
    'nav.chat': 'Chat',
    'nav.list': 'Liste',
    'nav.calendar': 'Kalender',
    'common.back': 'Zurück',
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.confirm': 'Bestätigen',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.search': 'Suchen',
    'common.loading': 'Laden...',
    'common.today': 'Heute',
    'common.tomorrow': 'Morgen',
    'common.yesterday': 'Gestern',
    'settings.title': 'Einstellungen',
    'settings.myPlan': 'Mein Plan',
    'settings.calendars': 'Kalender',
    'settings.notifications': 'Benachrichtigungen',
    'settings.smartTasks': 'Intelligente Aufgaben',
    'settings.specialFeatures': 'Sonderfunktionen',
    'settings.account': 'Konto',
    'settings.appearance': 'Erscheinung',
    'settings.language': 'Sprache',
    'settings.feedback': 'Feedback',
    'settings.about': 'Über',
    'settings.logout': 'Abmelden',
    'settings.kairo': 'HORAH',
    'settings.general': 'ALLGEMEIN',
    'settings.others': 'WEITERE',
    'settings.system': 'System',
    'language.title': 'Sprache',
    'language.search': 'Sprache suchen...',
    'language.note': 'Die Sprache wird auf die gesamte Horah-Oberfläche angewendet.',
    'plan.title': 'Mein Plan',
    'plan.free': 'Kostenlos',
    'plan.plus': 'PLUS',
    'plan.super': 'SUPER',
    'plan.premium': 'Horah Premium-Pläne',
    'plan.tryFree': '7 Tage kostenlos testen',
    'plan.eventsScheduled': 'Geplante Ereignisse',
    'plan.upgradeNow': 'Jetzt upgraden',
    'plan.monthly': 'Monatlich',
    'plan.yearly': 'Jährlich',
    'plan.saveYearly': 'Sparen Sie 17% bei jährlicher Abrechnung',
    'plan.features': 'Premium-Funktionen',
    'plan.faq': 'Fragen und Antworten',
    'plan.terms': 'Nutzungsbedingungen',
    'plan.privacy': 'Datenschutzrichtlinie',
    'plan.manageSubscription': 'Abonnement und Zahlungen verwalten',
    'plan.restorePurchases': 'Käufe wiederherstellen',
    'plan.manage': 'Verwalten',
    'appearance.light': 'Hell',
    'appearance.dark': 'Dunkel',
    'chat.placeholder': 'Nachricht schreiben...',
    'chat.greeting': 'Hallo! Was sollen wir heute planen?',
    'chat.today': 'Heute',
    'chat.yesterday': 'Gestern',
    'chat.errorConnect': 'Verbindung zur KI fehlgeschlagen',
    'chat.viewFullHistory': 'Vollständigen Verlauf anzeigen',
    'chat.startOfConversation': 'Beginn des Gesprächs',
    'chat.suggestion1': 'Grillfest mit Freunden diesen Samstag um 13 Uhr organisieren.',
    'chat.suggestion2': 'Arzttermin am Mittwoch um 9 Uhr.',
    'chat.suggestion3': 'Kaffee mit Sofia morgen um 16 Uhr in der Bäckerei.',
    'chat.suggestion4': 'Tickets für das Spiel am Wochenende kaufen.',
    'calendar.today': 'Heute',
    'calendar.tomorrow': 'Morgen',
    'calendar.noEvents': 'Keine Ereignisse',
    'calendar.todayIs': 'heute ist der',
    'calendar.allDay': 'Ganztägig',
    'calendar.weekdaySun': 'S',
    'calendar.weekdayMon': 'M',
    'calendar.weekdayTue': 'D',
    'calendar.weekdayWed': 'M',
    'calendar.weekdayThu': 'D',
    'calendar.weekdayFri': 'F',
    'calendar.weekdaySat': 'S',
    'about.title': 'Über',
    'about.terms': 'Nutzungsbedingungen',
    'about.privacy': 'Datenschutzrichtlinie',
    'about.faq': 'Häufig gestellte Fragen',
    'about.version': 'Version',
    // Events
    'event.created': 'Ereignis Erstellt',
    'event.updated': 'Ereignis Aktualisiert',
    'event.deleted': 'Ereignis Gelöscht',
    'event.completed': 'Ereignis Abgeschlossen',
    'event.callMe': 'Ruf mich an',
    'event.allDay': 'Ganztägig',
    'event.pastDate': 'Vergangenes Datum',
    'event.pastDateMessage': 'Dieses Datum und diese Uhrzeit sind bereits vergangen. Das Ereignis wurde erstellt, aber es werden keine Erinnerungen gesendet.',
    'event.tooClose': 'sehr nah',
    'event.eventAdded': 'Ereignis Hinzugefügt',
    'event.reminder': 'vorher',
    'event.oneHourBefore': '1 Stunde vorher',
    // Onboarding
    'onboarding.welcome': 'Hallo! Ich bin Horah, dein persönlicher Kalenderassistent. 📅\n\nErzähl mir von einem Ereignis, das du planen möchtest, und ich kümmere mich um den Rest!',
    'onboarding.firstEventSuccess': 'Perfekt! 🎉 Dein erstes Ereignis wurde erfolgreich erstellt.\n\nJetzt kannst du mir weiter von deinen Terminen erzählen, und ich organisiere alles für dich!',
  },
  'it-IT': {
    'nav.chat': 'Chat',
    'nav.list': 'Lista',
    'nav.calendar': 'Calendario',
    'common.back': 'Indietro',
    'common.save': 'Salva',
    'common.cancel': 'Annulla',
    'common.confirm': 'Conferma',
    'common.delete': 'Elimina',
    'common.edit': 'Modifica',
    'common.search': 'Cerca',
    'common.loading': 'Caricamento...',
    'common.today': 'Oggi',
    'common.tomorrow': 'Domani',
    'common.yesterday': 'Ieri',
    'settings.title': 'Impostazioni',
    'settings.myPlan': 'Il mio piano',
    'settings.calendars': 'Calendari',
    'settings.notifications': 'Notifiche',
    'settings.smartTasks': 'Attività Intelligenti',
    'settings.specialFeatures': 'Funzionalità Speciali',
    'settings.account': 'Account',
    'settings.appearance': 'Aspetto',
    'settings.language': 'Lingua',
    'settings.feedback': 'Feedback',
    'settings.about': 'Informazioni',
    'settings.logout': 'Esci',
    'settings.kairo': 'HORAH',
    'settings.general': 'GENERALE',
    'settings.others': 'ALTRO',
    'settings.system': 'Sistema',
    'language.title': 'Lingua',
    'language.search': 'Cerca lingua...',
    'language.note': 'La lingua verrà applicata a tutta l\'interfaccia Horah.',
    'plan.title': 'Il mio piano',
    'plan.free': 'Gratuito',
    'plan.plus': 'PLUS',
    'plan.super': 'SUPER',
    'plan.premium': 'Piani Horah Premium',
    'plan.tryFree': 'Prova gratuita per 7 giorni',
    'plan.eventsScheduled': 'Eventi programmati',
    'plan.upgradeNow': 'Aggiorna ora',
    'plan.monthly': 'Mensile',
    'plan.yearly': 'Annuale',
    'plan.saveYearly': 'Risparmia il 17% con la fatturazione annuale',
    'plan.features': 'Funzionalità Premium',
    'plan.faq': 'Domande e Risposte',
    'plan.terms': 'Termini di Servizio',
    'plan.privacy': 'Informativa sulla Privacy',
    'plan.manageSubscription': 'Gestisci abbonamento e pagamenti',
    'plan.restorePurchases': 'Ripristina acquisti',
    'plan.manage': 'Gestisci',
    'appearance.light': 'Chiaro',
    'appearance.dark': 'Scuro',
    'chat.placeholder': 'Scrivi un messaggio...',
    'chat.greeting': 'Ciao! Cosa programmiamo oggi?',
    'chat.today': 'Oggi',
    'chat.yesterday': 'Ieri',
    'chat.errorConnect': 'Connessione all\'IA fallita',
    'chat.viewFullHistory': 'Visualizza cronologia completa',
    'chat.startOfConversation': 'Inizio della conversazione',
    'chat.suggestion1': 'Organizzare un barbecue con amici sabato alle 13.',
    'chat.suggestion2': 'Appuntamento dal medico mercoledì alle 9.',
    'chat.suggestion3': 'Caffè con Sofia domani alle 16 in panetteria.',
    'chat.suggestion4': 'Comprare biglietti per la partita questo fine settimana.',
    'calendar.today': 'Oggi',
    'calendar.tomorrow': 'Domani',
    'calendar.noEvents': 'Nessun evento',
    'calendar.todayIs': 'oggi è il',
    'calendar.allDay': 'Tutto il giorno',
    'calendar.weekdaySun': 'D',
    'calendar.weekdayMon': 'L',
    'calendar.weekdayTue': 'M',
    'calendar.weekdayWed': 'M',
    'calendar.weekdayThu': 'G',
    'calendar.weekdayFri': 'V',
    'calendar.weekdaySat': 'S',
    'about.title': 'Informazioni',
    'about.terms': 'Termini di Servizio',
    'about.privacy': 'Informativa sulla Privacy',
    'about.faq': 'Domande Frequenti',
    'about.version': 'Versione',
    // Events
    'event.created': 'Evento Creato',
    'event.updated': 'Evento Aggiornato',
    'event.deleted': 'Evento Eliminato',
    'event.completed': 'Evento Completato',
    'event.callMe': 'Chiamami',
    'event.allDay': 'Tutto il giorno',
    'event.pastDate': 'Data passata',
    'event.pastDateMessage': 'Questa data e ora sono già passate. L\'evento è stato creato, ma non sarà possibile inviare promemoria.',
    'event.tooClose': 'molto vicino',
    'event.eventAdded': 'Evento Aggiunto',
    'event.reminder': 'prima',
    'event.oneHourBefore': '1 ora prima',
    // Onboarding
    'onboarding.welcome': 'Ciao! Sono Horah, il tuo assistente personale per l\'agenda. 📅\n\nRaccontami di un evento che vorresti programmare e io mi occuperò del resto!',
    'onboarding.firstEventSuccess': 'Perfetto! 🎉 Il tuo primo evento è stato creato con successo.\n\nOra puoi continuare a parlarmi dei tuoi impegni, e organizzerò tutto per te!',
  },
  'ja-JP': {
    'nav.chat': 'チャット',
    'nav.list': 'リスト',
    'nav.calendar': 'カレンダー',
    'common.back': '戻る',
    'common.save': '保存',
    'common.cancel': 'キャンセル',
    'common.confirm': '確認',
    'common.delete': '削除',
    'common.edit': '編集',
    'common.search': '検索',
    'common.loading': '読み込み中...',
    'common.today': '今日',
    'common.tomorrow': '明日',
    'common.yesterday': '昨日',
    'settings.title': '設定',
    'settings.myPlan': 'マイプラン',
    'settings.calendars': 'カレンダー',
    'settings.notifications': '通知',
    'settings.smartTasks': 'スマートタスク',
    'settings.specialFeatures': '特別機能',
    'settings.account': 'アカウント',
    'settings.appearance': '外観',
    'settings.language': '言語',
    'settings.feedback': 'フィードバック',
    'settings.about': '概要',
    'settings.logout': 'ログアウト',
    'settings.kairo': 'HORAH',
    'settings.general': '一般',
    'settings.others': 'その他',
    'settings.system': 'システム',
    'language.title': '言語',
    'language.search': '言語を検索...',
    'language.note': '言語はHorahインターフェース全体に適用されます。',
    'plan.title': 'マイプラン',
    'plan.free': '無料',
    'plan.plus': 'PLUS',
    'plan.super': 'SUPER',
    'plan.premium': 'Horah プレミアムプラン',
    'plan.tryFree': '7日間無料でお試し',
    'plan.eventsScheduled': '予定されたイベント',
    'plan.upgradeNow': '今すぐアップグレード',
    'plan.monthly': '月額',
    'plan.yearly': '年額',
    'plan.saveYearly': '年払いで17%節約',
    'plan.features': 'プレミアム機能',
    'plan.faq': 'よくある質問',
    'plan.terms': '利用規約',
    'plan.privacy': 'プライバシーポリシー',
    'plan.manageSubscription': 'サブスクリプションと支払いを管理',
    'plan.restorePurchases': '購入を復元',
    'plan.manage': '管理',
    'appearance.light': 'ライト',
    'appearance.dark': 'ダーク',
    'chat.placeholder': 'メッセージを入力...',
    'chat.greeting': 'こんにちは！今日は何を予定しますか？',
    'chat.today': '今日',
    'chat.yesterday': '昨日',
    'chat.errorConnect': 'AIへの接続に失敗しました',
    'chat.viewFullHistory': 'すべての履歴を見る',
    'chat.startOfConversation': '会話の始まり',
    'chat.suggestion1': '今週土曜日の13時に友人とバーベキューを企画する。',
    'chat.suggestion2': '水曜日の9時に医者の予約。',
    'chat.suggestion3': '明日の16時にパン屋でソフィアとコーヒー。',
    'chat.suggestion4': '今週末の試合のチケットを買う。',
    'calendar.today': '今日',
    'calendar.tomorrow': '明日',
    'calendar.noEvents': 'イベントなし',
    'calendar.todayIs': '今日は',
    'calendar.allDay': '終日',
    'calendar.weekdaySun': '日',
    'calendar.weekdayMon': '月',
    'calendar.weekdayTue': '火',
    'calendar.weekdayWed': '水',
    'calendar.weekdayThu': '木',
    'calendar.weekdayFri': '金',
    'calendar.weekdaySat': '土',
    'about.title': '概要',
    'about.terms': '利用規約',
    'about.privacy': 'プライバシーポリシー',
    'about.faq': 'よくある質問',
    'about.version': 'バージョン',
    // Events
    'event.created': 'イベント作成済み',
    'event.updated': 'イベント更新済み',
    'event.deleted': 'イベント削除済み',
    'event.completed': 'イベント完了',
    'event.callMe': '電話してください',
    'event.allDay': '終日',
    'event.pastDate': '過去の日付',
    'event.pastDateMessage': 'この日時はすでに過ぎています。イベントは作成されましたが、リマインダーを送信することはできません。',
    'event.tooClose': '非常に近い',
    'event.eventAdded': 'イベント追加済み',
    'event.reminder': '前',
    'event.oneHourBefore': '1時間前',
    // Onboarding
    'onboarding.welcome': 'こんにちは！Horahです、あなたの個人的なカレンダーアシスタントです。📅\n\n予定したいイベントについて教えてください、残りは私がやります！',
    'onboarding.firstEventSuccess': '完璧！🎉 最初のイベントが正常に作成されました。\n\nこれからも予定について教えてください、すべて整理します！',
  },
  'ko-KR': {
    'nav.chat': '채팅',
    'nav.list': '목록',
    'nav.calendar': '캘린더',
    'common.back': '뒤로',
    'common.save': '저장',
    'common.cancel': '취소',
    'common.confirm': '확인',
    'common.delete': '삭제',
    'common.edit': '편집',
    'common.search': '검색',
    'common.loading': '로딩 중...',
    'common.today': '오늘',
    'common.tomorrow': '내일',
    'common.yesterday': '어제',
    'settings.title': '설정',
    'settings.myPlan': '내 플랜',
    'settings.calendars': '캘린더',
    'settings.notifications': '알림',
    'settings.smartTasks': '스마트 작업',
    'settings.specialFeatures': '특별 기능',
    'settings.account': '계정',
    'settings.appearance': '외관',
    'settings.language': '언어',
    'settings.feedback': '피드백',
    'settings.about': '정보',
    'settings.logout': '로그아웃',
    'settings.kairo': 'HORAH',
    'settings.general': '일반',
    'settings.others': '기타',
    'settings.system': '시스템',
    'language.title': '언어',
    'language.search': '언어 검색...',
    'language.note': '언어는 전체 Horah 인터페이스에 적용됩니다.',
    'plan.title': '내 플랜',
    'plan.free': '무료',
    'plan.plus': 'PLUS',
    'plan.super': 'SUPER',
    'plan.premium': 'Horah 프리미엄 플랜',
    'plan.tryFree': '7일 무료 체험',
    'plan.eventsScheduled': '예정된 이벤트',
    'plan.upgradeNow': '지금 업그레이드',
    'plan.monthly': '월간',
    'plan.yearly': '연간',
    'plan.saveYearly': '연간 결제 시 17% 절약',
    'plan.features': '프리미엄 기능',
    'plan.faq': '자주 묻는 질문',
    'plan.terms': '서비스 약관',
    'plan.privacy': '개인정보 처리방침',
    'plan.manageSubscription': '구독 및 결제 관리',
    'plan.restorePurchases': '구매 복원',
    'plan.manage': '관리',
    'appearance.light': '라이트',
    'appearance.dark': '다크',
    'chat.placeholder': '메시지 입력...',
    'chat.greeting': '안녕하세요! 오늘 뭘 예약할까요?',
    'chat.today': '오늘',
    'chat.yesterday': '어제',
    'chat.errorConnect': 'AI 연결에 실패했습니다',
    'chat.viewFullHistory': '전체 기록 보기',
    'chat.startOfConversation': '대화 시작',
    'chat.suggestion1': '이번 주 토요일 오후 1시에 친구들과 바비큐 파티 준비하기.',
    'chat.suggestion2': '수요일 오전 9시 병원 예약.',
    'chat.suggestion3': '내일 오후 4시에 빵집에서 소피아와 커피.',
    'chat.suggestion4': '이번 주말 경기 티켓 구매하기.',
    'calendar.today': '오늘',
    'calendar.tomorrow': '내일',
    'calendar.noEvents': '이벤트 없음',
    'calendar.todayIs': '오늘은',
    'calendar.allDay': '종일',
    'calendar.weekdaySun': '일',
    'calendar.weekdayMon': '월',
    'calendar.weekdayTue': '화',
    'calendar.weekdayWed': '수',
    'calendar.weekdayThu': '목',
    'calendar.weekdayFri': '금',
    'calendar.weekdaySat': '토',
    'about.title': '정보',
    'about.terms': '서비스 약관',
    'about.privacy': '개인정보 처리방침',
    'about.faq': '자주 묻는 질문',
    'about.version': '버전',
    // Events
    'event.created': '이벤트 생성됨',
    'event.updated': '이벤트 업데이트됨',
    'event.deleted': '이벤트 삭제됨',
    'event.completed': '이벤트 완료',
    'event.callMe': '전화해 주세요',
    'event.allDay': '종일',
    'event.pastDate': '지난 날짜',
    'event.pastDateMessage': '이 날짜와 시간은 이미 지났습니다. 이벤트가 생성되었지만 알림을 보낼 수 없습니다.',
    'event.tooClose': '매우 가까움',
    'event.eventAdded': '이벤트 추가됨',
    'event.reminder': '전',
    'event.oneHourBefore': '1시간 전',
    // Onboarding
    'onboarding.welcome': '안녕하세요! 저는 Horah, 당신의 개인 캘린더 어시스턴트입니다. 📅\n\n예약하고 싶은 이벤트에 대해 말해주세요, 나머지는 제가 처리할게요!',
    'onboarding.firstEventSuccess': '완벽해요! 🎉 첫 번째 이벤트가 성공적으로 생성되었습니다.\n\n이제 계속해서 약속에 대해 말해주세요, 모든 것을 정리해 드릴게요!',
  },
  'zh-CN': {
    'nav.chat': '聊天',
    'nav.list': '列表',
    'nav.calendar': '日历',
    'common.back': '返回',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.confirm': '确认',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.search': '搜索',
    'common.loading': '加载中...',
    'common.today': '今天',
    'common.tomorrow': '明天',
    'common.yesterday': '昨天',
    'settings.title': '设置',
    'settings.myPlan': '我的计划',
    'settings.calendars': '日历',
    'settings.notifications': '通知',
    'settings.smartTasks': '智能任务',
    'settings.specialFeatures': '特殊功能',
    'settings.account': '账户',
    'settings.appearance': '外观',
    'settings.language': '语言',
    'settings.feedback': '反馈',
    'settings.about': '关于',
    'settings.logout': '退出',
    'settings.kairo': 'HORAH',
    'settings.general': '通用',
    'settings.others': '其他',
    'settings.system': '系统',
    'language.title': '语言',
    'language.search': '搜索语言...',
    'language.note': '语言将应用于整个Horah界面。',
    'plan.title': '我的计划',
    'plan.free': '免费',
    'plan.plus': 'PLUS',
    'plan.super': 'SUPER',
    'plan.premium': 'Horah高级计划',
    'plan.tryFree': '免费试用7天',
    'plan.eventsScheduled': '已安排的活动',
    'plan.upgradeNow': '立即升级',
    'plan.monthly': '月付',
    'plan.yearly': '年付',
    'plan.saveYearly': '年付节省17%',
    'plan.features': '高级功能',
    'plan.faq': '常见问题',
    'plan.terms': '服务条款',
    'plan.privacy': '隐私政策',
    'plan.manageSubscription': '管理订阅和付款',
    'plan.restorePurchases': '恢复购买',
    'plan.manage': '管理',
    'appearance.light': '浅色',
    'appearance.dark': '深色',
    'chat.placeholder': '输入消息...',
    'chat.greeting': '你好！今天我们安排什么？',
    'chat.today': '今天',
    'chat.yesterday': '昨天',
    'chat.errorConnect': '连接AI失败',
    'chat.viewFullHistory': '查看完整历史',
    'chat.startOfConversation': '对话开始',
    'chat.suggestion1': '本周六下午1点和朋友们组织烧烤。',
    'chat.suggestion2': '周三上午9点看医生。',
    'chat.suggestion3': '明天下午4点在面包店和索菲亚喝咖啡。',
    'chat.suggestion4': '买这个周末比赛的门票。',
    'calendar.today': '今天',
    'calendar.tomorrow': '明天',
    'calendar.noEvents': '无活动',
    'calendar.todayIs': '今天是',
    'calendar.allDay': '全天',
    'calendar.weekdaySun': '日',
    'calendar.weekdayMon': '一',
    'calendar.weekdayTue': '二',
    'calendar.weekdayWed': '三',
    'calendar.weekdayThu': '四',
    'calendar.weekdayFri': '五',
    'calendar.weekdaySat': '六',
    'about.title': '关于',
    'about.terms': '服务条款',
    'about.privacy': '隐私政策',
    'about.faq': '常见问题',
    'about.version': '版本',
    // Events
    'event.created': '活动已创建',
    'event.updated': '活动已更新',
    'event.deleted': '活动已删除',
    'event.completed': '活动已完成',
    'event.callMe': '打电话给我',
    'event.allDay': '全天',
    'event.pastDate': '过去的日期',
    'event.pastDateMessage': '此日期和时间已过。活动已创建，但无法发送提醒。',
    'event.tooClose': '非常接近',
    'event.eventAdded': '活动已添加',
    'event.reminder': '之前',
    'event.oneHourBefore': '1小时前',
    // Onboarding
    'onboarding.welcome': '你好！我是Horah，你的个人日历助手。📅\n\n告诉我你想安排的活动，剩下的交给我！',
    'onboarding.firstEventSuccess': '太棒了！🎉 你的第一个活动已成功创建。\n\n现在你可以继续告诉我你的约会，我会为你安排好一切！',
  },
};

// Detect device language
const detectDeviceLanguage = (): LanguageCode => {
  const savedLanguage = localStorage.getItem('kairo-language') as LanguageCode;
  if (savedLanguage && translations[savedLanguage]) {
    return savedLanguage;
  }
  
  // Get browser/device language
  const browserLang = navigator.language || (navigator as any).userLanguage;
  
  // Try exact match first
  if (translations[browserLang as LanguageCode]) {
    return browserLang as LanguageCode;
  }
  
  // Try matching just the language code (e.g., 'en' from 'en-GB')
  const langCode = browserLang.split('-')[0];
  const matchingLang = Object.keys(translations).find(key => 
    key.startsWith(langCode)
  ) as LanguageCode;
  
  if (matchingLang) {
    return matchingLang;
  }
  
  // Default to English if device language is not supported
  return 'en-US';
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguageState] = useState<LanguageCode>(() => detectDeviceLanguage());

  useEffect(() => {
    // Update HTML lang attribute
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = async (lang: LanguageCode) => {
    setLanguageState(lang);
    localStorage.setItem('kairo-language', lang);
    document.documentElement.lang = lang;
    
    // ✅ Sync language to database for MeLig/TTS to use
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (user) {
        await supabase
          .from('profiles')
          .update({ language: lang })
          .eq('id', user.id);
        console.log('[Language] Synced to database:', lang);
      }
    } catch (e) {
      console.error('[Language] Failed to sync to database:', e);
    }
  };

  const t = (key: string): string => {
    const langTranslations = translations[language];
    if (langTranslations && langTranslations[key]) {
      return langTranslations[key];
    }
    
    // Fallback to English
    const fallback = translations['en-US'][key];
    if (fallback) {
      return fallback;
    }
    
    // Return key if no translation found
    return key;
  };

  const getDateLocale = (): Locale => {
    return DATE_LOCALES[language] || ptBR;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, getDateLocale }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export { translations };
